#!/bin/sh

CONF_FILE=/etc/awds.conf
[ -e $CONF_FILE ] && source $CONF_FILE

modprobe tun

# use this for early detection of wrong configured stack:
export LD_BIND_NOW=1
export LD_LIBRARY_PATH=/usr/lib/awds/

cd $(dirname $0)

if [ $NET_DEV = auto ]
then
AUTODEV=$(grep -E -v "Inte|face" /proc/net/wireless | tr ":" " " | ( read a b; echo $a ) )
else
AUTODEV=$NET_DEV
fi

# argv1 can override the setting
DEVICE=${1:-$AUTODEV}

AESCCM=''
if [ x$USE_ENCRYPTION = xyes ]
then 
AESCCM="aesccm.so -k $KEY_FILE"
fi

AWDS_SHELL=''
[ "$USE_AWDS_SHELL" = yes ] && AWDS_SHELL='shell.so'

AWDS_TOPO=''
[ "$USE_TOPO_EXPORT" = yes ] && AWDS_TOPO='topowatch.so'


if [ "$DEV_CHANGE_WIRELESS_SETTINGS" = yes ]
then
    /sbin/ifconfig $DEVICE down
    /sbin/iwconfig $DEVICE mode ad-hoc channel $DEV_WIRELESS_CHANNEL essid $DEV_WIRELESS_ESSID
    /sbin/ifconfig $DEVICE up
fi


# echo Starting AWDS on $DEVICE

exec gea_start -i <<END
$AWDS_SHELL
daemon.so --pidfile /var/run/awds.pid
rawbasic.so $DEVICE
awdsrouting.so --name $HOSTNAME
#.libs/pinger.so
$AESCCM
tapiface2.so
$AWDS_TOPO
topolock.so
END

